//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyCFEntities : DbContext
    {
        public QuanLyCFEntities()
            : base("name=QuanLyCFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHD> CTHD { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<LoaiSP> LoaiSP { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<CTHD_GetALL_Result> CTHD_GetALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTHD_GetALL_Result>("CTHD_GetALL");
        }
    
        public virtual ObjectResult<CTHD_SanPhamTheoMaHD_Result> CTHD_SanPhamTheoMaHD(Nullable<int> maHD)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTHD_SanPhamTheoMaHD_Result>("CTHD_SanPhamTheoMaHD", maHDParameter);
        }
    
        public virtual ObjectResult<HoaDon_GetALL_Result> HoaDon_GetALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_GetALL_Result>("HoaDon_GetALL");
        }
    
        public virtual int HoaDon_LuuHoaDon(string tenKH, string tenSP, Nullable<double> donGia, Nullable<int> soLuong, string ghiChu, Nullable<System.DateTime> ngayMuaHang)
        {
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(double));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var ngayMuaHangParameter = ngayMuaHang.HasValue ?
                new ObjectParameter("NgayMuaHang", ngayMuaHang) :
                new ObjectParameter("NgayMuaHang", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HoaDon_LuuHoaDon", tenKHParameter, tenSPParameter, donGiaParameter, soLuongParameter, ghiChuParameter, ngayMuaHangParameter);
        }
    
        public virtual ObjectResult<LoaiSP_GetALL_Result> LoaiSP_GetALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoaiSP_GetALL_Result>("LoaiSP_GetALL");
        }
    
        public virtual int LoaiSP_ThemLoaiSP(string tenLoaiSP)
        {
            var tenLoaiSPParameter = tenLoaiSP != null ?
                new ObjectParameter("TenLoaiSP", tenLoaiSP) :
                new ObjectParameter("TenLoaiSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LoaiSP_ThemLoaiSP", tenLoaiSPParameter);
        }
    
        public virtual int LoaiSP_XoaLoaiSP(Nullable<int> maLoaiSP)
        {
            var maLoaiSPParameter = maLoaiSP.HasValue ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LoaiSP_XoaLoaiSP", maLoaiSPParameter);
        }
    
        public virtual ObjectResult<SanPham_SP_ChonSPTheoLoai1_Result> SanPham_SP_ChonSPTheoLoai1(Nullable<int> maLoaiSP)
        {
            var maLoaiSPParameter = maLoaiSP.HasValue ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SP_ChonSPTheoLoai1_Result>("SanPham_SP_ChonSPTheoLoai1", maLoaiSPParameter);
        }
    
        public virtual ObjectResult<SanPham_SP_ChonSPTheoTen_Result> SanPham_SP_ChonSPTheoTen(string tenSP)
        {
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SP_ChonSPTheoTen_Result>("SanPham_SP_ChonSPTheoTen", tenSPParameter);
        }
    
        public virtual ObjectResult<SanPham_SP_GETALL1_Result> SanPham_SP_GETALL1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SP_GETALL1_Result>("SanPham_SP_GETALL1");
        }
    
        public virtual int SanPham_SuaSP(Nullable<int> maSP, string tenSP, Nullable<double> gia, string ghiChu, Nullable<int> maLoaiSP, byte[] anh)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(double));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var maLoaiSPParameter = maLoaiSP.HasValue ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(int));
    
            var anhParameter = anh != null ?
                new ObjectParameter("Anh", anh) :
                new ObjectParameter("Anh", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SanPham_SuaSP", maSPParameter, tenSPParameter, giaParameter, ghiChuParameter, maLoaiSPParameter, anhParameter);
        }
    
        public virtual int SanPham_ThemSP(string tenSP, Nullable<double> gia, string ghiChu, Nullable<int> maLoaiSP, byte[] anh)
        {
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(double));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var maLoaiSPParameter = maLoaiSP.HasValue ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(int));
    
            var anhParameter = anh != null ?
                new ObjectParameter("Anh", anh) :
                new ObjectParameter("Anh", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SanPham_ThemSP", tenSPParameter, giaParameter, ghiChuParameter, maLoaiSPParameter, anhParameter);
        }
    
        public virtual int SanPham_XoaSP(Nullable<int> maSP)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SanPham_XoaSP", maSPParameter);
        }
    }
}
